### ISSUE TITLE
get_position()

### ISSUE THREAD

**Issue by dikshasaini11** [dikshasaini11/Group_E_Snakes_and_Ladders#13]
This function locates position of player on the board.

**Comment by Vidushi187** [comment]
This function is not being used in program due to change in requirements. The code for this function is as follows


/**\Brief function locates position of players on grid after each turn.
 * final position is displayed in form of cursor indicating player identity
 *
 */
int position()
{
	/*Initialize console window*/
    HANDLE hConsole;
    hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
   /* int type variables to store x, y positions of each player on the grid */
	int px1,px2,py1,py2;

	if (turn%2==0){//if turn no is even, this is used to indicate that it is player one's turn
		if (p1==0){//!< Player 1's game has not started so no change in position
		}else{
			/*calculate x, y position of player based on p1*/
			px1=(p1-1)%10+1;
			py1=(p1-1)/10+1;
			if (py1%2==1)
			{
				p1_ini.xpos = 2+(px1-1)*8;
				p1_ini.ypos= 38-(py1-1)*4;
			}
			else
			{
				p1_ini.xpos = 74-(px1-1)*8;
				p1_ini.ypos = 38-(py1-1)*4;
			}

			/*set properties of text to be displayed*/
			//SetConsoleTextAttribute(hconsole,FOREGROUND_RED+FOREGROUND_RED+FOREGROUND_RED+FOREGROUND_GREEN);
			/*print final position of player 1*/
			locate(p1_ini.xpos,p1_ini.ypos);
			printf(" %s\n","P1");

			Sleep(100);//might remove
		}
	}else{
		/*similar functionality for player 2*/
		if (p2==0){
		}else
		{
			px2=(p2-1)%10+1;py2=(p2-1)/10+1;
			if (py2%2==1)
			{
				p2_ini.xpos = 2+(px2-1)*8;
				p2_ini.ypos = 38-(py2-1)*4;
			}
			else
			{
				p2_ini.xpos = 74-(px2-1)*8;
				p2_ini.ypos = 38-(py2-1)*4;
			}

			//SetConsoleTextAttribute(hconsole,53);
			locate(p2_ini.xpos,p2_ini.ypos);
			printf(" %s\n","P2");
		}
	}

    return 0;
}
